### ISSUE TITLE
Use `WeakMap` for Object Memoization?

### ISSUE THREAD

**Issue by sno2** [antfu/nuxt-server-fn#1]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap

Currently, the caching algorithm holds all of the arguments passed to state objects forever.  However, this can be optimized in cases, for example, where the arguments are extremely large.  The cases of bloat can also be hard to spot; for example, a class may contain a property to another object that has a reference to a very complex object.  The strongly holds onto the arguments, so the complex object is unable to be garbage collected.  The use of the `WeakMap` would make the cache still hold the arguments while they are not GC'd, but it will try to access values from the cache if they are available.

Therefore, we could have two caches, one would be the `Map` which contains the cache for the primitive and non-object server function calls and the other would be the `WeakMap` which includes the cache for object function calls.  Thanks

Edit: The use-case also passes [MDN's "Avoid where possible" clause for weak references](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef#avoid_where_possible).

**Comment by antfu** [comment]
We use `useState` to cache the state per-app for both the client and server sides. So at the initial load, the fetch is done on the server side while the state will be passed to the client so the client doesn't need to fetch it again. WeakMap won't be serializable so probably not an idea in this case. You can always opt-out the caching mechanism as you want. We will improve the APIs to make them more intuitive as we go.

**Comment by antfu** [comment]
Should be improved
